# Generated by Django 6.0.6 on 2026-06-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
