# Generated by Django 6.0.6 on 2026-06-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
