# Generated by Django 6.0.6 on 2026-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
