# Generated by Django 6.0.6 on 2026-06-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_color_alter_product_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='pagina_pedidos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
