# Generated by Django 6.0.6 on 2026-06-19 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_suplier_pagina_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name='ProductSuplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.suplier')),
            ],
        ),
    ]
