# Generated by Django 6.0.6 on 2026-06-19 21:18

from django.db import migrations, models

def copiar_datos_intermedios(apps,sheme_editor):
    Producto = apps.get_model('inventory', 'Product')
    ProductoProveedor = apps.get_model('inventory', 'ProductSuplier')

    for producto in Producto.objects.all():

        for proveedor in producto.proveedores.all():
            print(proveedor)
            ProductoProveedor.objects.create(
                product = producto,
                suplier = proveedor,
            )

def eliminar_intermediarios(apps,sheme_editor):
    ProductoProveedor = apps.get_model('inventory','ProductSuplier')
    ProductoProveedor.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stockmovement_fecha_productsuplier'),
    ]

    operations = [
        migrations.RunPython(copiar_datos_intermedios, eliminar_intermediarios
        ),
    

    ]