# Generated by Django 6.0.6 on 2026-06-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20260619_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='proveedores',
        ),
    ]
