# Generated by Django 6.0.6 on 2026-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_product_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proveedores',
            field=models.ManyToManyField(blank=True, through='inventory.ProductSuplier', to='inventory.suplier'),
        ),
    ]
